-- MySQL Script generated by MySQL Workbench
-- 2018年12月24日 星期一 16时36分03秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema china_used_car_estimate
--
-- 中国二手车估值系统数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `invest` DEFAULT CHARACTER SET utf8 ;
USE `invest` ;

CREATE TABLE IF NOT EXISTS `invest`.`etoro` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Product` varchar(50) DEFAULT NULL COMMENT '商品名称',
  `Period` varchar(50) DEFAULT NULL COMMENT '周期类型',
  `InstrumentID` INT DEFAULT NULL COMMENT '平台ID',
  `FromDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '时间节点',
  `Open` decimal(10,4) DEFAULT NULL COMMENT '开盘价',
  `High` decimal(10,4) DEFAULT NULL COMMENT '最高价',
  `Low` decimal(10,4) DEFAULT NULL COMMENT '最低价',
  `Close` decimal(10,4) DEFAULT NULL COMMENT '收盘价',
  PRIMARY KEY (`id`),
  UNIQUE KEY i_Product_Period_FromDate(Product, Period, FromDate)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='商品期货价格数据';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
